using Checkout.Authentication.Standalone.Common.Requests;
using System.Collections.Generic;

namespace Checkout.Authentication.Standalone.PUTSessionsIdCollectData.Requests.AppRequest
{
    /// <summary>
    /// Update a session
    /// Update a session by providing information about the environment.
    /// </summary>
    public class AppRequest : AbstractUpdateASessionRequest
    {
        /// <summary>
        /// Initializes a new instance of the App class.
        /// </summary>
        public AppRequest() : base(ChannelType.App)
        {
        }

        /// <summary>
        /// Universally unique ID created upon all installations and updates of the 3DS Requestor App on a consumer
        /// device. This will be newly generated and stored by the 3DS SDK for each installation or update.
        /// [Required]
        /// 36 characters
        /// </summary>
        public string SdkAppId { get; set; }

        /// <summary>
        /// Indicates maximum amount of time (in minutes) for all exchanges
        /// [Required]
        /// &gt;= 5
        /// </summary>
        public int SdkMaxTimeout { get; set; }

        /// <summary>
        /// Public key component of the ephemeral key pair generated by the 3DS SDK and used to establish session keys
        /// between the 3DS SDK and ACS. Refer to https://tools.ietf.org/html/rfc7517#appendix-A.1
        /// [Required]
        /// </summary>
        public SdkEphemPubKey.SdkEphemPubKey SdkEphemPubKey { get; set; }

        /// <summary>
        /// A JSON web encryption (JWE) object in compact serialization, containing data encrypted by the SDK for the
        /// Directory Server to decrypt.
        /// [Required]
        /// &lt;= 64000
        /// </summary>
        public string SdkEncryptedData { get; set; }

        /// <summary>
        /// Identifies the vendor and version for the 3DS SDK that is integrated in a 3DS Requestor App, assigned by
        /// EMVCo when the 3DS SDK is approved.
        /// [Required]
        /// &lt;= 32
        /// </summary>
        public string SdkReferenceNumber { get; set; }

        /// <summary>
        /// Universally unique transaction identifier assigned by the 3DS SDK to identify a single transaction
        /// [Required]
        /// 36 characters
        /// </summary>
        public string SdkTransactionId { get; set; }

        /// <summary>
        /// Lists all of the SDK interface types that the device supports for displaying specific challenge user
        /// interfaces within the SDK
        /// [Required]
        /// </summary>
        public SdkInterfaceType? SdkInterfaceType { get; set; }

        /// <summary>
        /// Lists all the user interface elements that the cardholder's device supports for displaying specific
        /// challenge user interfaces within the SDK
        /// [Required]
        /// </summary>
        public IList<SdkUiElementsType> SdkUiElements { get; set; }
    }
}