using Checkout.Common;
using System.Collections.Generic;

namespace Checkout.Payments
{
    public class PaymentProcessing
    {
        /// <summary>
        /// A unique identifier for the authorization that is submitted to the card scheme during processing.
        /// [Optional]
        /// </summary>
        public string RetrievalReferenceNumber { get; set; }

        /// <summary>
        /// A unique identifier for the transaction generated by the acquirer.
        /// [Optional]
        /// </summary>
        public string AcquirerTransactionId { get; set; }

        /// <summary>
        /// A code representing the follow-up action to take with the payment, as recommended by Checkout.com.
        /// [Optional]
        /// </summary>
        public string RecommendationCode { get; set; }

        /// <summary>
        /// The scheme the transaction was processed with.
        /// [Optional]
        /// </summary>
        public string Scheme { get; set; }

        /// <summary>
        /// The Mastercard Merchant Advice Code (MAC), which contains additional information about the
        /// transaction. For example, the MAC can inform you if the transaction was performed using a
        /// consumer non-reloadable prepaid card or a consumer single-use virtual card. For declined
        /// transactions, the MAC also indicates whether the payment can be retried and how long to wait.
        /// [Optional]
        /// </summary>
        public string PartnerMerchantAdviceCode { get; set; }

        /// <summary>
        /// The original authorization response code sent by the scheme, also referred to as the raw
        /// response code. This differs from the recommendation_code value, which is provided by
        /// Checkout.com and is standardized across all schemes.
        /// [Optional]
        /// </summary>
        public string PartnerResponseCode { get; set; }

        /// <summary>
        /// Unique order identification of an Afterpay payment.
        /// [Optional]
        /// </summary>
        public string PartnerOrderId { get; set; }

        /// <summary>
        /// The partner session identifier associated with the payment.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public string PartnerSessionId { get; set; }

        /// <summary>
        /// The client token returned by the partner for client-side initialization.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public string PartnerClientToken { get; set; }

        /// <summary>
        /// Unique identification of a payment provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerPaymentId { get; set; }

        /// <summary>
        /// The type of Primary Account Number (PAN) used for the payment. DPAN indicates network
        /// token was used, FPAN indicates the full card was used.
        /// [Optional]
        /// </summary>
        public PanProcessedType? PanTypeProcessed { get; set; }

        /// <summary>
        /// A payload used to continue processing for multi-step payment flows.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public string ContinuationPayload { get; set; }

        /// <summary>
        /// The Payment Unique Number (PUN) assigned to the payment.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public string Pun { get; set; }

        /// <summary>
        /// Status of a payment provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerStatus { get; set; }

        /// <summary>
        /// Unique transaction identification provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerTransactionId { get; set; }

        /// <summary>
        /// Error codes provided by partner.
        /// [Optional]
        /// </summary>
        public IList<string> PartnerErrorCodes { get; set; }

        /// <summary>
        /// Error description provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerErrorMessage { get; set; }

        /// <summary>
        /// Authorization code provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerAuthorizationCode { get; set; }

        /// <summary>
        /// Authorization response code provided by partner.
        /// [Optional]
        /// </summary>
        public string PartnerAuthorizationResponseCode { get; set; }

        /// <summary>
        /// Surcharge amount applied to the transaction in minor units.
        /// [Optional]
        /// &gt;= 0
        /// </summary>
        public long? SurchargeAmount { get; set; }

        /// <summary>
        /// Indicates whether the fallback_source field was used for the payment.
        /// [Optional]
        /// </summary>
        public bool? FallbackSourceUsed { get; set; }

        /// <summary>
        /// The flag indicating if Checkout Network Token was available for the payment.
        /// [Optional]
        /// </summary>
        public bool? CkoNetworkTokenAvailable { get; set; }

        /// <summary>
        /// The country where the purchase was made. ISO 3166-1 alpha-2 country code.
        /// [Optional]
        /// &lt;= 2 characters
        /// </summary>
        public CountryCode? PurchaseCountry { get; set; }

        /// <summary>
        /// The foreign retailer amount the merchant applied to the transaction, in the minor currency unit.
        /// [Optional]
        /// &gt;= 0
        /// </summary>
        public long? ForeignRetailerAmount { get; set; }

        /// <summary>
        /// The merchant category code (MCC) associated with the payment.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public string MerchantCategoryCode { get; set; }

        /// <summary>
        /// The merchant identifier that was configured with the scheme and used for the payment.
        /// [Optional]
        /// </summary>
        public string SchemeMerchantId { get; set; }

        /// <summary>
        /// The transaction identifier to track a payment request.
        /// [Optional]
        /// </summary>
        public string ReconciliationId { get; set; }

        /// <summary>
        /// Information about the payment aggregator.
        /// [Optional]
        /// </summary>
        public ProcessingAggregator Aggregator { get; set; }

        /// <summary>
        /// Indicates whether the payment is an Account Funding Transaction.
        /// Not documented in the public spec for this response, kept for backward compatibility.
        /// [Optional]
        /// </summary>
        public bool? Aft { get; set; }

        /// <summary>
        /// The scheme transaction link identifier. Returned for Mastercard transactions when the scheme
        /// provides a link identifier that ties together related transactions on the network
        /// (see Mastercard Transaction Link Identifier documentation).
        /// [Optional]
        /// </summary>
        public string SchemeTransactionLinkId { get; set; }
    }
}
