namespace Checkout.Payments
{
    /// <summary>
    /// Information related to the processing of the payment
    /// </summary>
    public class ProcessingResponse
    {
        /// <summary>
        /// Gets or sets the retrieval reference number - a unique identifier for the authorization that is submitted to the card scheme during processing
        /// </summary>
        /// <value></value>
        public string RetrievalReferenceNumber { get; set; }
        
        /// <summary>
        /// Gets or sets the unique identifier for the transaction generated by the acquirer
        /// </summary>
        public string AcquirerTransactionId { get; set; }
    }
}