namespace Checkout.HandlePaymentsAndPayouts.Payments.Common.Source.
    KnetSource
{
    /// <summary>
    /// knet source Class
    /// The source of the payment
    /// </summary>
    public class KnetSource : AbstractSource
    {
        /// <summary>
        /// Initializes a new instance of the KnetSource class.
        /// </summary>
        public KnetSource() : base(SourceType.Knet)
        {
        }

        /// <summary>
        /// Required for KNet Gateway payments.
        /// This field enables the issuer's site to select the consumer's preferred language. For example, the language
        /// selected on the merchant's site – if the issuer's site supports it. Code list in accordance with ISO 639-1.
        /// (Arabic = 'ar', English = 'en'). Note that 'ar' corresponds to 'ARA' and 'en' to 'USA'. Both values accepted
        /// by KNet Gateway.
        /// [Optional]
        /// </summary>
        public LanguageType? Language { get; set; }

        /// <summary>
        /// User-defined field that can be used to pass and store any additional transaction data required to be
        /// archived with the transaction and available as a searching criterion. Only alphanumeric characters and
        /// spaces are allowed.
        /// [Optional]
        /// </summary>
        public string UserDefinedFieldOne { get; set; }

        /// <summary>
        /// User-defined field can be used to pass and store any additional transaction data required to be archived
        /// with the transaction and available as a searching criterion. Only alphanumeric characters and spaces are
        /// allowed.
        /// [Optional]
        /// </summary>
        public string UserDefinedFieldTwo { get; set; }

        /// <summary>
        /// User-defined field can be used to pass and store any additional transaction data required to be archived
        /// with the transaction and available as a searching criterion. Only alphanumeric characters and spaces are
        /// allowed. Note that this field must be omitted when the card_token field is not empty. This restriction
        /// exists because a card token is passed to KNet Gateway as user_defined_field3.
        /// [Optional]
        /// </summary>
        public string UserDefinedFieldThree { get; set; }

        /// <summary>
        /// User-defined field can be used to pass and store any additional transaction data required to be archived
        /// with the transaction and available as a searching criterion. Only alphanumeric characters and spaces are
        /// allowed.
        /// [Optional]
        /// </summary>
        public string UserDefinedFieldFour { get; set; }

        /// <summary>
        /// User-defined field can be used to pass and store any additional transaction data required to be archived
        /// with the transaction and available as a searching criterion. Only alphanumeric characters and spaces are
        /// allowed. Note that this field must be omitted when the ptlf field is not empty. This restriction exists
        /// because a PTLF value is passed to KNet Gateway as user_defined_field5.
        /// [Optional]
        /// </summary>
        public string UserDefinedFieldFive { get; set; }

        /// <summary>
        /// This token allows re-usage of card details for multiple payments. This 8-digit token should be generated by
        /// a merchant. When a subsequent payment is initialized with the same card token, a customer is presented with
        /// two options. The customer can choose to pay with KFast (doesn't need to enter card details again), or with
        /// KNet as usual. The payment flow stays the same i.e. a merchant should redirect a customer to the redirect
        /// URL which is provided in the payment creation response. Note that user_defined_field3 must be omitted when
        /// the card_token field is not empty. This restriction exists because a card token is passed to KNet Gateway as
        /// user_defined_field3.
        /// [Optional]
        /// ^[0-9]{8}$
        /// </summary>
        public string CardToken { get; set; }

        /// <summary>
        /// This is an ID for merchant PTLF functionality tracking. Only alphanumeric characters are allowed. Note that
        /// user_defined_field5 must be omitted when the ptlf field is not empty. This restriction exists because a PTLF
        /// value is passed to KNet Gateway as user_defined_field5.
        /// [Optional]
        /// &lt;= 45
        /// </summary>
        public string Ptlf { get; set; }

        /// <summary>
        /// The payment identifier assigned by KNet Gateway.
        /// [Optional]
        /// </summary>
        public string KnetPaymentId { get; set; }

        /// <summary>
        /// The state of the payment, returned by KNet Gateway after the customer is redirected from the payment page.
        /// [Optional]
        /// </summary>
        public string KnetResult { get; set; }

        /// <summary>
        /// The state of the payment, returned by KNet Gateway in the response from the payment inquiry. This field is
        /// populated in rare cases when the redirection from the payment page did not occur properly.
        /// [Optional]
        /// </summary>
        public string InquiryResult { get; set; }

        /// <summary>
        /// The result transaction reference, given by some banks/institutions.
        /// [Optional]
        /// </summary>
        public string BankReference { get; set; }

        /// <summary>
        /// The transaction identifier assigned by KNet Gateway.
        /// [Optional]
        /// </summary>
        public string KnetTransactionId { get; set; }

        /// <summary>
        /// The resulting authorization code from the issuing bank.
        /// [Optional]
        /// </summary>
        public string AuthCode { get; set; }

        /// <summary>
        /// The auth response code / reason code relating to the issuing bank authorization code.
        /// [Optional]
        /// </summary>
        public string AuthResponseCode { get; set; }

        /// <summary>
        /// The transaction date in the authorization system format, with the value defined by the issuing bank, so may
        /// not match the actual transaction date. The format is MMDD.
        /// [Optional]
        /// </summary>
        public string PostDate { get; set; }

        /// <summary>
        /// The Address Verification Response returned from the address verification service.
        /// [Optional]
        /// </summary>
        public string Avr { get; set; }

        /// <summary>
        /// The KNET error code for transaction processing.
        /// [Optional]
        /// </summary>
        public string Error { get; set; }

        /// <summary>
        /// The KNET text detail for the error, including an error code.
        /// [Optional]
        /// </summary>
        public string ErrorText { get; set; }
    }
}