using System.Runtime.Serialization;

namespace Checkout.PaymentMethods.Entities
{
    public enum PaymentMethodType
    {
        [EnumMember(Value = "accel")] Accel,
        [EnumMember(Value = "ach")] Ach,
        [EnumMember(Value = "alipay_cn")] AlipayCn,
        [EnumMember(Value = "alipay_hk")] AlipayHk,
        [EnumMember(Value = "alipay_plus")] AlipayPlus,
        [EnumMember(Value = "alma")] Alma,
        [EnumMember(Value = "amex")] Amex,
        [EnumMember(Value = "bancontact")] Bancontact,
        [EnumMember(Value = "bank_redirects")] BankRedirects,
        [EnumMember(Value = "boost")] Boost,
        [EnumMember(Value = "bpi")] Bpi,
        [EnumMember(Value = "bnpl")] Bnpl,
        [EnumMember(Value = "cartes_bancaires")] CartesBancaires,
        [EnumMember(Value = "card_scheme")] CardScheme,
        [EnumMember(Value = "china_union_pay")] ChinaUnionPay,
        [EnumMember(Value = "connect_wallet")] ConnectWallet,
        [EnumMember(Value = "dana")] Dana,
        [EnumMember(Value = "dci")] Dci,
        [EnumMember(Value = "diners")] Diners,
        [EnumMember(Value = "discover")] Discover,
        [EnumMember(Value = "eps")] Eps,
        [EnumMember(Value = "gcash")] Gcash,
        [EnumMember(Value = "ideal")] Ideal,
        [EnumMember(Value = "jcb")] Jcb,
        [EnumMember(Value = "kakaopay")] Kakaopay,
        [EnumMember(Value = "klarna")] Klarna,
        [EnumMember(Value = "knet")] Knet,
        [EnumMember(Value = "mada")] Mada,
        [EnumMember(Value = "mastercard")] Mastercard,
        [EnumMember(Value = "mbway")] Mbway,
        [EnumMember(Value = "multibanco")] Multibanco,
        [EnumMember(Value = "nyce")] Nyce,
        [EnumMember(Value = "omannet")] Omannet,
        [EnumMember(Value = "p24")] P24,
        [EnumMember(Value = "paypal")] Paypal,
        [EnumMember(Value = "paypay")] Paypay,
        [EnumMember(Value = "pulse")] Pulse,
        [EnumMember(Value = "qpay")] Qpay,
        [EnumMember(Value = "rabbit_line_pay")] RabbitLinePay,
        [EnumMember(Value = "sepa")] Sepa,
        [EnumMember(Value = "sequra")] Sequra,
        [EnumMember(Value = "shazam")] Shazam,
        [EnumMember(Value = "star")] Star,
        [EnumMember(Value = "stcpay")] Stcpay,
        [EnumMember(Value = "swish")] Swish,
        [EnumMember(Value = "tamara")] Tamara,
        [EnumMember(Value = "tng")] Tng,
        [EnumMember(Value = "truemoney")] Truemoney,
        [EnumMember(Value = "upi")] Upi,
        [EnumMember(Value = "visa")] Visa,
        [EnumMember(Value = "wallet")] Wallet,
        [EnumMember(Value = "wechatpay")] Wechatpay
    }
}