namespace Checkout.Authentication.Standalone.POSTSessions.Requests.RequestASessionRequest.ChannelData.AppChannelData.SdkEphemPubKey
{
    /// <summary>
    /// sdk_ephem_pub_key
    /// Public key component of the ephemeral key pair generated by the 3DS SDK and used to establish session keys
    /// between the 3DS SDK and ACS. Refer to https://tools.ietf.org/html/rfc7517#appendix-A.1
    /// </summary>
    public class SdkEphemPubKey
    {
        /// <summary>
        /// The key type.
        /// [Optional]
        /// </summary>
        public string Kty { get; set; }

        /// <summary>
        /// The type of elliptic curve.
        /// [Optional]
        /// <= 40
        /// </summary>
        public string Crv { get; set; }

        /// <summary>
        /// x coordinate of the elliptic curve that is base64url-encoded.
        /// [Optional]
        /// <= 100
        /// </summary>
        public string X { get; set; }

        /// <summary>
        /// y coordinate of the elliptic curve that is base64url-encoded.
        /// [Optional]
        /// <= 100
        /// </summary>
        public string Y { get; set; }
    }
}