namespace Checkout.Payments.Setups.Entities
{
    /// <summary>
    /// The Blik payment method's details and configuration.
    /// </summary>
    public class Blik : PaymentMethodBase
    {
        /// <summary>
        /// The 6-digit BLIK code generated by the customer's banking app.
        /// [Optional] writeOnly
        /// Pattern: ^[0-9]{6}$
        /// </summary>
        public string PartnerCode { get; set; }
    }
}
